
#application name
spring.application.name=Warhammer

#the connection string used for access to the mongodb database, stored via an enviroment variable
#do not commit the enviromental variable into this access point
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
#the specied database accessed from the cluster
spring.mongodb.database=warhammer







